### ISSUE TITLE
Replace accessor expression syntax with block syntax

### ISSUE THREAD

**Issue by CaulyKan** [SharpGenTools/SharpGenTools#102]
Hi,

Although I know that SharpGenTools is designed to use with VS2017, For some reason i have to use VS2015 and .net46 for developing my program. After some research, I found it can be used with VS2015 with some workarounds and generates code as expected. 

However the last obstacle is that the generated c# code uses a accessor expression syntax introduces in C# 7.0, which is not supported by VS2015. For example,
```
typedef struct
{
	double i[3];
} double3;
```
will generates the following C# 7.0 code:
```
        public System.Double[] I
        {
            get => _I ?? (_I = new System.Double[3]);
            private set => _I = value;
        }
```
which I think the following code are same functional but better compatible:
```
        public System.Double[] I
        {
            get { return _I ?? (_I = new System.Double[3]); }
            private set { _I = value; }
        }
```

Thank you!

**Comment by andrew-boyarshin** [comment]
SharpGen 2.0 will require C# 9.0 (for function pointers), as per discussion with @SharpGenTools/core. Older versions require C# 7.0, which is low enough requirement given that you can move bindings into separate project and build it with latest .NET 5+ SDK. You don't need IDE there. Generated public API surface is compatible with .NET Framework 4.5 and .NET Standard 1.1, so VS2015 projects can consume built assemblies without issues.
