### ISSUE TITLE
SharpGen doesn't understand return values

### ISSUE THREAD

**Issue by Alovchin91** [SharpGenTools/SharpGenTools#113]
I have a very simple and very common example where SharpGenTools fails to generate correct code.

Consider the following C++ code:

```cpp
typedef struct my_struct {} my_struct;

int create_struct(my_struct** result);
```

It's a very common pattern - a factory function that returns pointer to a pointer to a struct.

The generated C# code, however, looks like this:

```cs
/// <summary>
/// No documentation.
/// </summary>
/// <param name = "result">No documentation.</param>
/// <returns>No documentation.</returns>
/// <unmanaged>int create_struct([In] my_struct** result)</unmanaged>
/// <unmanaged-short>create_struct</unmanaged-short>
public static unsafe System.Int32 create_struct(SharpGenBugs.MyStruct result)
{
    System.Int32 __result__;
    __result__ = create_struct_(&result);
    return __result__;
}

[System.Runtime.InteropServices.DllImportAttribute("example", EntryPoint = "create_struct", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
private unsafe static extern int create_struct_(void *param0);
```

As you can see, the double pointer is not respected and the generated code tries to write a pointer to the actual struct.

I have attached a sample project to the issue.

[shaprgentools-bugs.zip](https://github.com/SharpGenTools/SharpGenTools/files/3113964/shaprgentools-bugs.zip)

**Comment by jkoritzinsky** [comment]
How would you like this to be marshalled? Since (at least by my reading of the native signature) that the native function allocates the memory (something like the following), SharpGen doesn't currently have a good way to model the memory ownership model without exposing raw pointers.

```cpp
int create_struct(my_struct** result)
{
    *result = new my_struct();
    return 0;
}
```

**Comment by Alovchin91** [comment]
@jkoritzinsky This is true, I'm not sure how this can be correctly modeled in pure C# without using pointers. What I would expect in this case though, is that SharpGen would generate a correct p/invoke signature (`void **` instead of `void *` for extern method) and maybe generate an `IntPtr` for the public method signature.

**Comment by Alovchin91** [comment]
This is not the only problem with returning values by SharpGen though.

Here's another simple example (based on the attached one) where SharpGen generates incorrect code:

Native:
```cpp
my_struct* create_struct_2();
```

Mapping:
```xml
<map function="create_struct_2" group="SharpGenBugs.Functions" name="$0" dll='"example"' />
```

Generated struct:
```cs
[...]
public partial struct MyStruct
{
}
```

Generated function:
```cs
public static unsafe SharpGenBugs.MyStruct create_struct_2()
{
    SharpGenBugs.MyStruct __result__;
    __result__ = create_struct_2_();
    return __result__;
}

[System.Runtime.InteropServices.DllImportAttribute("example", EntryPoint = "create_struct_2", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
private unsafe static extern SharpGenBugs.MyStruct create_struct_2_();
```

As you see, SharpGen returns the structure itself by value when it should return the pointer to the structure (or `ref`, I don't really know).

The XML generated by CastXML contains this information:

```xml
<function name="create_struct_2" call-conv="cdecl">
    <return typename="my_struct" ptr="*" const="false" array="false" />
</function>
```

So apparently it's SharpGen who doesn't understand (or respect) that the return value is a pointer.

Hence I'll change the name of the issue back to what it was originally 😃

**Comment by jkoritzinsky** [comment]
I'm taking a look. As a workaround, you can add a mapping rule to your mapping file for these parameters/return values to map them as follows:

```
<map param="param::pattern" type="void" />
```

That will map them to IntPtr.

**Comment by Alovchin91** [comment]
@jkoritzinsky Thank you! I'm not sure how to map the return value in my example though.

**Comment by Alovchin91** [comment]
@jkoritzinsky Thank you! I'm not sure how to map the return value in my example though.

**Comment by jkoritzinsky** [comment]
To map the return value, you can do: `<map function="function::pattern" type="void" />`
