### ISSUE TITLE
how can i map a macro to a C# function

### ISSUE THREAD

**Issue by sgf** [SharpGenTools/SharpGenTools#128]
such like this:
```C++
#define WINDIVERT_IPHDR_SET_FRAGOFF(hdr, val)               \
    do                                                      \
    {                                                       \
        (hdr)->FragOff0 = (((hdr)->FragOff0) & 0x00E0) |    \
            ((val) & 0xFF1F);                               \
    }                                                       \
    while (FALSE)
```

im trying find any doc on https://sharpgentools.readthedocs.io/en/latest/custom-mapping.html#mapping-functions
but not found

**Comment by sgf** [comment]
another question is the Gen Code looks same like PInvoke.
so what different with PInvoke? seems cant find calli code.

**Comment by jkoritzinsky** [comment]
SharpGenTools doesn't support mapping function-like macros that don't map to expressions since there's no good generalized way to do so.

If you're just mapping functions, then you'll get code very similar to P/Invokes. If you're mapping interfaces, you'll get the `calli` instructions injected into your code for calls into the vtables of the native objects.

**Comment by sgf** [comment]
> SharpGenTools不支持映射类似函数的宏，这些宏不映射到表达式，因为没有很好的通用方法。
> 
> 如果您只是映射函数，那么您将获得与P / Invokes非常相似的代码。如果您正在映射接口，那么您将获得`calli`注入代码的指令，以便调用本机对象的vtable。

thank you

**Comment by sgf** [comment]
> SharpGenTools doesn't support mapping function-like macros that don't map to expressions since there's no good generalized way to do so.
> 
> If you're just mapping functions, then you'll get code very similar to P/Invokes. If you're mapping interfaces, you'll get the `calli` instructions injected into your code for calls into the vtables of the native objects.

maybe maybe can be map to a dynamic functions
