### ISSUE TITLE
XAudio issue with recent 10.0.18362.0 SDK

### ISSUE THREAD

**Issue by amerkoleci** [SharpGenTools/SharpGenTools#147]
Hi,

I'm working on adding XAudio support in my last Vortice.Windows version, the last 10.0.18362.0 SDK xaudio2.h has issue with latest myget SharpGen SDK version.

EXTERN_C const GUID DECLSPEC_SELECTANY IID_IXAudio2 = __uuidof(IXAudio2);
EXTERN_C const GUID DECLSPEC_SELECTANY IID_IXAudio2Extension = __uuidof(IXAudio2Extension);

The error is: cannot call operator __uuidof on a type with no GUID.

This is the commit (https://github.com/amerkoleci/Vortice.Windows/commit/df1666653aa8a17fa2485ee7395de00e9aed5929)

Thanks

**Comment by amerkoleci** [comment]
Not related to this issue, when do you plan to release last version of SDK and Runtime + COM part?

**Comment by EssenRoc** [comment]
+1
