### ISSUE TITLE
Cannot publish symbols to nuget

### ISSUE THREAD

**Issue by amerkoleci** [SharpGenTools/SharpGenTools#160]
Following the guide here: https://docs.microsoft.com/it-it/nuget/create-packages/symbol-packages-snupkg

I cannot publish symbols on nuget as SharpGen probably modifies the assembly and nuget complains abount invalid checksum.

Any thouhts?

**Comment by jkoritzinsky** [comment]
Hmmm. I don’t know if there’s a good way to fix this without waiting for function pointers and changing SharpGenTools to use them.

**Comment by andrew-boyarshin** [comment]
Fixed in 2.0.
