### ISSUE TITLE
PlatformNotSupported being launched

### ISSUE THREAD

**Issue by amerkoleci** [SharpGenTools/SharpGenTools#162]
Not sure if its something related to update VisualStudio or latest .NET core SDK but i'm getting compilation issues:

https://github.com/amerkoleci/Vortice.Windows/commit/f6e51ebf9464784a20f107c7cc2ae4fd31890dab

Can you help me out please? Its quite urgent @jkoritzinsky

**Comment by jkoritzinsky** [comment]
What’s the stack trace?

**Comment by amerkoleci** [comment]
If you clone Vortice.Windows repo and run the command from repo root:

dotnet pack src --configuration Release --output build/packages

You will get lot of those errors:

C:\Users\Riccardo Sanguin\.nuget\packages\sharpgentools.sdk\1.2.1\build\SharpGenTools.Sdk.targets(173,5): error MSB4018: errore imprevisto dell'attività "GenerateExtensionHeaders". [E:\test\managed\Vortice.Windows\src\Vortice.Runtime.COM\Vortice.Runtime.COM.csproj]
C:\Users\Riccardo Sanguin\.nuget\packages\sharpgentools.sdk\1.2.1\build\SharpGenTools.Sdk.targets(173,5): error MSB4018: System.PlatformNotSupportedException: Operation is not supported on this platform. [E:\test\managed\Vortice.Windows\src\Vortice.Runtime.COM\Vortice.Runtime.COM.csproj]
C:\Users\Riccardo Sanguin\.nuget\packages\sharpgentools.sdk\1.2.1\build\SharpGenTools.Sdk.targets(173,5): error MSB4018:    at System.Runtime.InteropServices.OSPlatform.get_Windows() [E:\test\managed\Vortice.Windows\src\Vortice.Runtime.COM\Vortice.Runtime.COM.csproj]
C:\Users\Riccardo Sanguin\.nuget\packages\sharpgentools.sdk\1.2.1\build\SharpGenTools.Sdk.targets(173,5): error MSB4018:    at SharpGen.Parser.SdkResolver.ResolveStdLib(String version)+MoveNext() [E:\test\managed\Vortice.Windows\src\Vortice.Runtime.COM\Vortice.Runtime.COM.csproj]
C:\Users\Riccardo Sanguin\.nuget\packages\sharpgentools.sdk\1.2.1\build\SharpGenTools.Sdk.targets(173,5): error MSB4018:    at SharpGenTools.Sdk.Tasks.SharpGenCppTaskBase.LoadConfig(ConfigFile config) [E:\test\managed\Vortice.Windows\src\Vortice.Runtime.COM\Vortice.Runtime.COM.csproj]
C:\Users\Riccardo Sanguin\.nuget\packages\sharpgentools.sdk\1.2.1\build\SharpGenTools.Sdk.targets(173,5): error MSB4018:    at SharpGenTools.Sdk.Tasks.SharpGenTaskBase.Execute() [E:\test\managed\Vortice.Windows\src\Vortice.Runtime.COM\Vortice.Runtime.COM.csproj]
C:\Users\Riccardo Sanguin\.nuget\packages\sharpgentools.sdk\1.2.1\build\SharpGenTools.Sdk.targets(173,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [E:\test\managed\Vortice.Windows\src\Vortice.Runtime.COM\Vortice.Runtime.COM.csproj]
C:\Users\Riccardo Sanguin\.nuget\packages\sharpgentools.sdk\1.2.1\build\SharpGenTools.Sdk.targets(173,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [E:\test\managed\Vortice.Windows\src\Vortice.Runtime.COM\Vortice.Runtime.COM.csproj]

**Comment by amerkoleci** [comment]
Found the issue!

The issue was of using .NET SDK 3.1.201, downgrading to 3.1.101 fixed.

Thanks

**Comment by nerzhulart** [comment]
Hi! Is this solved on fresh .Net core? I've faced with this on 3.1.301.

**Comment by jkoritzinsky** [comment]
I believe this may be fixed with the nightly builds of SharpGenTools but I haven't verified it myself.
