### ISSUE TITLE
Unexpected compiler version, expected Clang 10.0.0 or newer

### ISSUE THREAD

**Issue by MosGeo** [SharpGenTools/SharpGenTools#192]
Beginner here. I am trying to use SharpGenTools on LibCZI (https://github.com/zeiss-microscopy/libCZI). Following the instructions, I  added the Mapping.xml  as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<config id="MyMapping" xmlns="urn:SharpGen.Config">
    <assembly>MyAssembly</assembly>
    <namespace>MyAssembly.Namespace</namespace>
    <depends>SharpGen.Runtime</depends>
    <include-dir override="true">$(THIS_CONFIG_PATH)/Native/Src/libCZi/</include-dir>
    <include file="libCZI.h" namespace="MyAssembly.MyNamespace" attach="true" />
</config>
```

I am getitng the following error:

`Error CX0001 STL1000: Unexpected compiler version, expected Clang 10.0.0 or newer. LibCZISharp	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\yvals_core.h	520	
`

Any guidance would be helpful. Visual Studio 2019 is installed including Clang. I am fairly new to this interop game.

Edit: one more thing, LibCZI compiles normally in VS2019 using MSVC.

**Comment by andrew-boyarshin** [comment]
I had a quick look at the library you're trying to generate the bindings for. It provides only C++ headers incompatible with any sort of traditional native binding generators (with private fields, non-virtual methods). You can check ClangSharp, I'm not sure if it supports your case fully (you can try asking a question at ClangSharp GitHub Discussions). CppSharp claims to support such cases, even though my personal experience with that project was negative. I hope this works for you, and that one day, SharpGen will support these scenarios. For now, I'm afraid it's a known SharpGen limitation.
