### ISSUE TITLE
Unexpected compiler version, expected Clang 11.0.0 or newer

### ISSUE THREAD

**Issue by Elringus** [SharpGenTools/SharpGenTools#195]
Getting the error with latest SharpGen beta and a simple cpp header (one virtual method with std::string return type and no args). Looks like embedded CastXML is associated with and old clang version. I've noticed a similar issue where you've mentioned something about adding a way to specify clang version; is it possible at the moment?

**Comment by andrew-boyarshin** [comment]
You can specify custom CastXML version (`$(CastXmlPath)`), one that is based on the latest Clang version. I haven't tested the scenario with latest STL headers though.

**Comment by Elringus** [comment]
Thank you! I was able to specify custom CastXML binary using this property. It still failed to build due to "unknown type" error for std::string, though.

For anyone having the same issue, you can download latest CastXML binaries at https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/57b5de948d777f10f2696370 or build them with this script https://github.com/CastXML/CastXMLSuperbuild and then specify path to the binary with the following (in .csproj):
```
<PropertyGroup>
    <CastXmlPath>path\to\castxml.exe</CastXmlPath>
</PropertyGroup>
```
