### ISSUE TITLE
Could use some assistance getting started

### ISSUE THREAD

**Issue by kmgallahan** [SharpGenTools/SharpGenTools#197]
Hi. I'm attempting to create a wrapper lib using SharpGenTools. I've followed the documentation to create a basic Mapping.xml file, modified my .csproj file, and added SharpGenTools references. 

On building the project I get a .dll, but it appears to have no usable content, and the build output provides no clues as to if anything even happened.

Here is the a repo with the VS solution: https://github.com/kmgallahan/AllSystemsGo.SonyCameraRemoteSDK_SGT

I don't expect assistance making the wrapper work, I'm just not clear on how to proceed.

**Comment by andrew-boyarshin** [comment]
It appears, you didn't actually include SharpGen SDK. Only the Runtime, which is now referenced automatically by SDK.

**Comment by andrew-boyarshin** [comment]
I've submitted PR to your repo. 2 of the `remove enum-item` entries are due to bug in SharpGen, to be fixed in `beta.10`. `map enum-item="Cr(.+)" name-tmp="$1"` is a hack to prevent generating identifiers starting with digits (enum name being trimmed away from e.g. `CrAspectRatio`). `map function` is mandatory since there are functions present (need to attach to some class and specify the DLL name).

**Comment by kmgallahan** [comment]
@andrew-boyarshin Ah, I see what my mistake was. On seeing this in the [installation instructions](https://sharpgentools.readthedocs.io/en/latest/getting-started.html#installing-sharpgentools):

```
dotnet add package SharpGenTools.Sdk
dotnet add package SharpGen.Runtime
```

I used the VS Nuget browser to find the packages to install them. However, I have it set to include prerelease by default, and the prerelease package failed to install because it is an SDK style project (which I didn't even notice). The runtime installed successfully which is why it was sitting there alone.

---

I'll try to keep questions to a minimum as there is plenty of documentation to reference. Thanks for your help!
