### ISSUE TITLE
Suggestion: Adopt GitHub Discussions

### ISSUE THREAD

**Issue by kmgallahan** [SharpGenTools/SharpGenTools#198]
[GitHub Discussions](https://docs.github.com/en/discussions) is a newish feature that is great for handling non-issue related items, such as [questions regarding SharpGenTools usage](https://github.com/SharpGenTools/SharpGenTools/issues/197).

IMO all repos should adopt them to keep the issues section more focused & actionable, while providing a dedicated area that is more approachable for general communication.

**Comment by andrew-boyarshin** [comment]
Good idea, done, thanks!

**Comment by kmgallahan** [comment]
FYI, you can [convert issues to discussions](https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion), in case any are open ones that you'd like to migrate.
