### ISSUE TITLE
Invalid validation SG0018

### ISSUE THREAD

**Issue by MikhailGorobets** [SharpGenTools/SharpGenTools#225]
Hi @jkoritzinsky,
I got this error when generating C# code from C++:
```
The field [Name] in structure [TextureDesc] has pointer alignment within a structure that requires explicit layout. 
This situation cannot be handled on both 32-bit and 64-bit architectures. 
This structure needs manual layout (remove fields from definition) and write them manually in xml mapping files
```

Below are examples of when this happens.
### Example 1, when inherited classes, the base class has a pointer
```cpp

struct DeviceObjectAttribs {
    const char* Name = nullptr;
};

struct TextureDesc: public DeviceObjectAttribs {
    uint32_t Width = {};

    uint32_t Height = {};
};
```
For example this case passes the validation check
```cpp
struct TextureDesc  {
    const char* Name = nullptr;

    uint32_t Width = {};

    uint32_t Height  = {};
};

```

### Example 2, when there is a pointer and union in the class fields

```cpp
struct TextureDesc  {
    const char* Name = nullptr;

    uint32_t Width = {};

    uint32_t Height  = {};
    
    union
    {
        uint32_t ArraySize = {};

        uint32_t Depth;
    };
};

```

An invalid validation error occurs at this point in the code.
https://github.com/SharpGenTools/SharpGenTools/blob/dc9e43d002946d708373ebf5b8a86a0fdd8059af/SharpGen/Transform/StructTransform.cs#L224

I commented out this branch of code and got correct results.

**Comment by Cutano** [comment]
Hi @MikhailGorobets,
I'm running into the same issue, have you already solve it, or is there any best practice to avoid such a problem?

**Comment by MikhailGorobets** [comment]
@Cutano Hello. The problem still exists. The C++ standard doesn't define the alignment of class fields when inheriting. 
Therefore, I think that the examples aren't particularly valid. The first example generates a valid code when validation is disabled, but the second example generates a valid code.

**Comment by Cutano** [comment]
> I removed all structure fields that give errors and defined all structure fields manually

Thanks!
That helps a lot!

**Comment by MikhailGorobets** [comment]
@Cutano I have fixed this problem.  You can try this package https://www.nuget.org/packages/Diligent-SharpGenTools.Sdk
If the structure contains a union and a string, then the manual marshaler still needs to be written
