### ISSUE TITLE
Release with trimming support

### ISSUE THREAD

**Issue by kant2002** [SharpGenTools/SharpGenTools#229]
Currently released version 2.0.0-beta11 does not have trimming annotations for net5.0 assembly which problematic if used with NativeAOT because it force to use RD.xml file which is bandaind. can we have 2.0.0-beta12 where this trimming annotations would be included?

**Comment by amerkoleci** [comment]
Thats what I'm trying to do with all changes:
https://www.nuget.org/packages/SharpGenTools.Sdk/2.0.0-beta.12

**Comment by zaafar** [comment]
Just for reference, please read https://github.com/SharpGenTools/SharpGenTools/pull/223

**Comment by amerkoleci** [comment]
Just release https://www.nuget.org/packages/SharpGen.Runtime.COM/2.0.0-beta.13

**Comment by dmirmilshteyn** [comment]
Seriously, thank you! Appears to be working great in Vortice now.

**Comment by amerkoleci** [comment]
Yes it works, glad to see this happening!
