### ISSUE TITLE
Bugs with inheritance

### ISSUE THREAD

**Issue by MikhailGorobets** [SharpGenTools/SharpGenTools#230]
I found two bugs with inheritance. The first one was with incorrect validation when inheriting. The second one was with an error during recursive inheritance. I fixed these errors, and committed the corresponding changes. I apologize, currently I have no time to submit it as a separate PR.
https://github.com/MikhailGorobets/Diligent-SharpGenTools/commit/eab3736db83875ce50e3df74edf899db06c7b139
https://github.com/MikhailGorobets/Diligent-SharpGenTools/commit/0db39bf2e81544111de52f43efe54c940b0e6cd3

**Comment by amerkoleci** [comment]
Thanks,
I'm merging your changes from your fork.
