### ISSUE TITLE
Dependency on PolySharp is propagated to consumers

### ISSUE THREAD

**Issue by YoshiRulz** [SharpGenTools/SharpGenTools#236]
Updating from [`2.0.0-beta.12`](https://www.nuget.org/packages/SharpGen.Runtime/2.0.0-beta.12#dependencies-body-tab) to [`2.0.0-beta.13`](https://www.nuget.org/packages/SharpGen.Runtime/2.0.0-beta.13#dependencies-body-tab) pulls in `PolySharp` as an extra transitive dependency (due to https://github.com/SharpGenTools/SharpGenTools/commit/19b94d30aecb7469d5c0c877ffe475031caa68ca). This conflicts with the polyfill lib we use.

I believe this can be fixed by adding `PrivateAssets="all"` to each `<PackageReference/>`.

**Comment by amerkoleci** [comment]
Feel free to submit PR, thanks!

**Comment by amerkoleci** [comment]
Last version fixes this issues, can you try and report back?

Thanks!
