### ISSUE TITLE
High CPU and disk usage

### ISSUE THREAD

**Issue by amerkoleci** [SharpGenTools/SharpGenTools#60]
When compiling SharpDX everytime the CPU and disk usage is very high and almost 100%, any possibility to run the generation offline maybe and then just use VS for compile?

**Comment by amerkoleci** [comment]
Latest

**Comment by amerkoleci** [comment]
Latest

**Comment by amerkoleci** [comment]
I saw that the latest 1.0.4-ci410 is faster but I'm not able to compile SharpDX with those.

**Comment by jkoritzinsky** [comment]
What issue are you hitting in compiling SharpDX? Can you attach it here?

**Comment by amerkoleci** [comment]
D3D12_DESCRIPTOR_TABLE_INNER size not marshalled or something similar, not at the PC now
