### ISSUE TITLE
A method returning a pointer-sized type should never be marked as a large return type.

### ISSUE THREAD

**Issue by jkoritzinsky** [SharpGenTools/SharpGenTools#72]
Pointer return types are never too large to be returned normally, so we need to use the regular return machinery for those return types.

**Comment by xoofx** [comment]
There is something I don't understand even when looking at the old code (SharpGen in SharpDX), as the `PointerSize` is declared with a size of 8 while `CsMethod.IsReturnStructLarge` is testing for this size against 4, which should say that it was a large type, while it should not...

Btw, can I easily debug SharpGenTools inside SharpDX?

**Comment by xoofx** [comment]
Ah ok, found it that was in the `mapping-core.xml`:

```xml
    <bind from="SIZE_T" to="SharpDX.PointerSize" marshal="System.IntPtr"/>
    <bind from="SSIZE_T" to="SharpDX.PointerSize" marshal="System.IntPtr"/>
```

while the new `mapping-core.xml` is missing this:

https://github.com/sharpdx/SharpDX/blob/36446065142df0df6b6098b34efd4950204cbb37/Source/SharpDX/Mapping-core.xml#L129-L130

Do you recall why you had to remove the marshal information?

**Comment by jkoritzinsky** [comment]
There ended up being a code-child bug (as seen in #73). Im currently doing some refactoring of the marshaling code that will correctly fix this issue.

**Comment by jkoritzinsky** [comment]
And you should be able to debug SharpGenTools by attaching a debugger to the MSBuild instance when building. I believe the packages include pdbs.

**Comment by jkoritzinsky** [comment]
I've fixed this correctly in master and added unit tests to verify code-gen behavior.
