### ISSUE TITLE
Update built-in CastXML

### ISSUE THREAD

**Issue by jkoritzinsky** [SharpGenTools/SharpGenTools#87]
The built-in CastXML version now fails to compile the newest MSVC++ standard library. The library now recognizes Clang-based compilers and errors out if the version is too old. The version of Clang built into the version of CastXML in the repo is pre-Clang 7, so it errors out.

**Comment by sherpya** [comment]
Still unreleased? On nuget I only see v1.1.2

**Comment by jkoritzinsky** [comment]
Yeah I haven’t put out a new release yet. I’ve just been super busy with a new job and haven’t had the time for SharpGenTools that I want.

**Comment by sherpya** [comment]
I've copied directory from master the error is different, looks like castxml does not parses c++14 stuff, there is an option to make it handle c++14 code?

**Comment by jkoritzinsky** [comment]
Did you just copy CastXML from master or did you build packages from master? There’s some stuff to simplify picking a C++ version in master but I don’t think it’s in the last release.

**Comment by sherpya** [comment]
I've copied the CastXML directory from master to packages\SharpGenTools.Sdk.1.1.2\tools in my project, just to make a quick test, if you are talking about CastXmlArg added in master, I don't have it, I'll try to build SharpGenTools from master
